### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by lidaming1** [magic-research/magic-animate#118]
Hi. When start project: python -m magicanimate.pipelines.animation --config configs/prompts/animation.yaml
have some error :
```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
E:\JupyterNoteBook\lidaming\magic-animate\magicanimate\pipelines\pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is depreca
ted. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\utils\_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "C:\ProgramData\anaconda3\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/pretrained_models/stable-diffusion-v1-5/resolve/main/tokenizer/tokenizer_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\transformers\utils\hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1374, in hf_hub_download
    raise head_call_error
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 426, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\ProgramData\anaconda3\lib\site-packages\huggingface_hub\utils\_errors.py", line 320, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-65825bb9-3d5247bb676aecf77ad7cda5;fe795558-d4a6-43f1-a8c9-6243d2815fcd)

Repository Not Found for url: https://huggingface.co/pretrained_models/stable-diffusion-v1-5/resolve/main/tokenizer/tokenizer_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\JupyterNoteBook\lidaming\magic-animate\magicanimate\pipelines\animation.py", line 282, in <module>
    run(args)
  File "E:\JupyterNoteBook\lidaming\magic-animate\magicanimate\pipelines\animation.py", line 271, in run
    main(args)
  File "E:\JupyterNoteBook\lidaming\magic-animate\magicanimate\pipelines\animation.py", line 75, in main
    tokenizer = CLIPTokenizer.from_pretrained(config.pretrained_model_path, subfolder="tokenizer")
  File "C:\ProgramData\anaconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 1951, in from_pretrained
    resolved_config_file = cached_file(
  File "C:\ProgramData\anaconda3\lib\site-packages\transformers\utils\hub.py", line 410, in cached_file
    raise EnvironmentError(
OSError: pretrained_models/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

**Comment by lidaming1** [comment]
https://github.com/magic-research/magic-animate/issues/13
