### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory pretrained_models/stable-diffusion-v1-5.

### ISSUE THREAD

**Issue by jygkh** [magic-research/magic-animate#12]
(manimate) ryan@DESKTOP-81PKUNM:/mnt/d/python/magic-animate-main$ bash scripts/animate.sh
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/manimate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ryan/miniconda3/envs/manimate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/python/magic-animate-main/magicanimate/pipelines/animation.py", line 282, in <module>
    run(args)
  File "/mnt/d/python/magic-animate-main/magicanimate/pipelines/animation.py", line 271, in run
    main(args)
  File "/mnt/d/python/magic-animate-main/magicanimate/pipelines/animation.py", line 76, in main
    text_encoder = CLIPTextModel.from_pretrained(config.pretrained_model_path, subfolder="text_encoder")
  File "/home/ryan/miniconda3/envs/manimate/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2805, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/ryan/miniconda3/envs/manimate/lib/python3.8/site-packages/transformers/modeling_utils.py", line 458, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

I downloaded the models from the updated links from #2

**Comment by mp3pintyo** [comment]
[Read my install guide](https://github.com/magic-research/magic-animate/issues/13)

**Comment by FurkanGozukara** [comment]
finally released full scripts including auto DensePose maker : https://github.com/magic-research/magic-animate/issues/44
