### ISSUE TITLE
Installation guide for Windows

### ISSUE THREAD

**Issue by mp3pintyo** [magic-research/magic-animate#13]
**Install Ubuntu on WSL2 on Windows 10**
https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#7-enjoy-ubuntu-on-wsl

**git lfs install:**
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install

**ffmpeg install:**
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install ffmpeg

git clone https://github.com/magic-research/magic-animate.git
cd magic-animate
pip install nvidia-pyindex
pip3 install -r requirements.txt

**you create the folder structure you need**
pretrained_models
git lfs clone https://huggingface.co/zcxu-eric/MagicAnimate

pretrained_models/sd-vae-ft-mse
https://huggingface.co/stabilityai/sd-vae-ft-mse/resolve/main/diffusion_pytorch_model.safetensors
https://huggingface.co/stabilityai/sd-vae-ft-mse/resolve/main/config.json

pretrained_models/stable-diffusion-v1-5
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors

stable-diffusion-v1-5/tokenizer
All file

stable-diffusion-v1-5/text_encoder 
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/text_encoder/pytorch_model.bin

stable-diffusion-v1-5/unet
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/config.json
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.bin

stable-diffusion-v1-5/scheduler
https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/scheduler/scheduler_config.json

**Run:**
python3 -m demo.gradio_animate
or
bash scripts/animate.sh

**Comment by FurkanGozukara** [comment]
can you try with this raw video instead of pre shared motion video


https://github.com/magic-research/magic-animate/assets/19240467/b1900be5-7ed8-4072-bcbb-b959fcdcaae2

**Comment by mp3pintyo** [comment]
> can you try with this raw video instead of pre shared motion video
> ex2.mp4

But this is not a DensePose video. This definitely won't work.

**Comment by FurkanGozukara** [comment]
> DensePose

ok how we gonna generate DensePose video?

**Comment by mp3pintyo** [comment]
> > DensePose
> 
> ok how we gonna generate DensePose video?

Whit this: https://github.com/facebookresearch/detectron2

**Comment by FurkanGozukara** [comment]
> > > DensePose
> > 
> > 
> > ok how we gonna generate DensePose video?
> 
> Whit this: https://github.com/facebookresearch/detectron2

Thanks opened an issue thread there

Do you know how?

https://github.com/facebookresearch/detectron2/issues/5167

**Comment by zcxu-eric** [comment]
Hi, we acutally don't have window platform to test the installation and inference.  You can refer to https://github.com/magic-research/magic-animate/issues/18 for generating your own DensePose seuqnces. Thanks.

**Comment by Rokkonrol** [comment]
Is there no way to install it without utilizing WSL2? I've been trying for around 2 hours to get it to work via Anaconda and/or Powershell on Windows 11, but it always come up with errors.

I'm wanting to run it on my cloud PC, but the service I use (Shadow) does not allow nested virtualization, so I can't utilize WSL2. Super frustrating.

**Comment by makemefeelgr8** [comment]
I tried installing it natively with 0 luck. The anaconda way fails, as there are about 10 libraries missing. As for the pip way `pip3 install -r requirements.txt` it fails with:

```log
ERROR: Could not find a version that satisfies the requirement nvidia-cudnn-cu11==8.5.0.96 (from versions: 0.0.1.dev5, 8.9.4.19, 8.9.4.25, 8.9.5.29)
ERROR: No matching distribution found for nvidia-cudnn-cu11==8.5.0.96
```

They [dropped windows support](https://www.tensorflow.org/install/pip#windows-native) in tensorflow (talk about being out of touch), so the only way to fix this would be to install an older version of tensorflow. I'm no python developer, and I haven't found where the package version is specified. Thus, this is all the progress I made.

**Comment by Priestru** [comment]
urgh

```
/home/yuuru/magic-animate/magicanimate/pipelines/pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Traceback (most recent call last):
  File "/home/yuuru/miniconda3/envs/manimate/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yuuru/miniconda3/envs/manimate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yuuru/magic-animate/magicanimate/pipelines/animation.py", line 282, in <module>
    run(args)
  File "/home/yuuru/magic-animate/magicanimate/pipelines/animation.py", line 271, in run
    main(args)
  File "/home/yuuru/magic-animate/magicanimate/pipelines/animation.py", line 75, in main
    tokenizer = CLIPTokenizer.from_pretrained(config.pretrained_model_path, subfolder="tokenizer")
  File "/home/yuuru/miniconda3/envs/manimate/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1838, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'pretrained_models/stable-diffusion-v1-5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'pretrained_models/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```

**Comment by mp3pintyo** [comment]
> urgh
>   File "/home/yuuru/magic-animate/magicanimate/pipelines/animation.py", line 75, in main
>     tokenizer = CLIPTokenizer.from_pretrained(config.pretrained_model_path, subfolder="tokenizer")
'pretrained_models/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
> ```

Please read back! I described that you need to download the tokenizer folder.

**Comment by Priestru** [comment]
> Please read back! I described that you need to download the tokenizer folder.

Yeah, I sure did. Trying again from scratch.

**Comment by FurkanGozukara** [comment]
> Is there no way to install it without utilizing WSL2? I've been trying for around 2 hours to get it to work via Anaconda and/or Powershell on Windows 11, but it always come up with errors.
> 
> I'm wanting to run it on my cloud PC, but the service I use (Shadow) does not allow nested virtualization, so I can't utilize WSL2. Super frustrating.

there is a way

i spent hours to make it work yesterday like more than 6 hours

works with regular venv and python 3.10.x

[can be downloaded from here](https://www.patreon.com/posts/magic-animate-94098751) i am preparing a tutorial and working on automatic dense pose generator right now 

![image](https://github.com/magic-research/magic-animate/assets/19240467/91dd83bf-83cb-4ee1-a46c-c7b512aa1feb)

**Comment by FurkanGozukara** [comment]
finally released full scripts including auto DensePose maker : https://github.com/magic-research/magic-animate/issues/44

**Comment by huiyichanmian** [comment]
There is an issue with installing on Windows, you can view this video：
https://www.bilibili.com/video/BV1ig4y1f7BQ/?share_source=copy_web&vd_source=842db193ae3e8fc29019a57821e30000

**Comment by friendlyFriend4000** [comment]
https://github.com/sdbds/magic-animate-for-windows

Here is a one click solution without any paywalls. 

I think it's bad taste to use the issue section for promoting oneself economic endeavors because it goes against the spirit of open source. You cannot take open source content  and put it behind a paywall in good faith. It doesn't matter if you worked 24hours straight. The project creators have probably worked much longer.

**Comment by Augus202312** [comment]
> > urgh
> > 文件“/home/yuuru/magic-animate/magicanimate/pipelines/animation.py”，第 75 行，在主
> > tokenizer = CLIPTokenizer.from_pretrained(config.pretrained_model_path, subfolder="tokenizer") 
> > 'pretrained_models/stable-diffusion-v1 -5' 是包含 CLIPTokenizer 分词器所有相关文件的目录的正确路径。
> 
> 请回读！我描述过您需要下载 tokenizer 文件夹。
![image](https://github.com/magic-research/magic-animate/assets/153266602/7c362102-1337-470b-8283-7a3c07e41d93)

**Comment by dabaonidetou** [comment]
i install models base on this way ,but it still appear

root@7dc8f2bdf8ef:/home/runner/magic-animate# python3 -m demo.gradio_animate
/home/runner/magic-animate/magicanimate/pipelines/pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Initializing MagicAnimate Pipeline...
loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5/unet ...
### missing keys: 560; 
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 108, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/magic-animate/demo/gradio_animate.py", line 19, in <module>
    animator = MagicAnimate()
  File "/home/runner/magic-animate/demo/animate.py", line 64, in __init__
    self.appearance_encoder = AppearanceEncoderModel.from_pretrained(config.pretrained_appearance_encoder_path, subfolder="appearance_encoder").cuda()
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 641, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 113, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

**Comment by friendlyFriend4000** [comment]
> > > urgh
> > > 文件“/home/yuuru/magic-animate/magicanimate/pipelines/animation.py”，第 75 行，在主
> > > tokenizer = CLIPTokenizer.from_pretrained(config.pretrained_model_path, subfolder="tokenizer")
> > > 'pretrained_models/stable-diffusion-v1 -5' 是包含 CLIPTokenizer 分词器所有相关文件的目录的正确路径。
> > 
> > 
> > 请回读！我描述过您需要下载 tokenizer 文件夹。
> > ![image](https://private-user-images.githubusercontent.com/153266602/288998001-7c362102-1337-470b-8283-7a3c07e41d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjM3OTMsIm5iZiI6MTcwMjQ2MzQ5MywicGF0aCI6Ii8xNTMyNjY2MDIvMjg4OTk4MDAxLTdjMzYyMTAyLTEzMzctNDcwYi04MjgzLTdhM2MwN2U0MWQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMDMxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDNjM2MyNjM0ODEzNTFjM2U0MmMxNGI4OGQ1ZGIwMzNlZGZhODk0ZGU2Njk0YTUwNGFhOTZhYmYxZGUzZDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TL90tssC8VdNmC5iEEppaWG6RrzFKFPT5cV3kH1SDhg)

open an issue here
https://github.com/sdbds/magic-animate-for-windows/issues
