### ISSUE TITLE
Can't upload custom Densepose to the gradio demo

### ISSUE THREAD

**Issue by chen-rn** [magic-research/magic-animate#39]
Hi, I get an error when I try to upload any densepose videos to the Gradio demo.

I've tried resizing the video to 512 x 512. Using mp4 format. Or even downloading the videos attached in the example and re-uploading them.

All of them returns the following error.
Using huggingface spaces.

```
UnboundLocalError: local variable 'size' referenced before assignment
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/utils.py", line 673, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 62, in read_video
    size = int(size)
UnboundLocalError: local variable 'size' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/user/.pyenv/versions/3.8.18/lib/python3.8/site-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

**Comment by chen-rn** [comment]
Nevermind, this seems to be working on the newer commit.
