### ISSUE TITLE
please fix depedency for windows 

### ISSUE THREAD

**Issue by EKI-INDRADI** [magic-research/magic-animate#50]
remove nvidia-cudnn-cu11==8.5.0.96
from requirements.txt because for linux (manual install cuda ncnn for windows) [solved]

remove nvidia-nccl-cu11==2.14.3
from requirements.txt because for linux (manual install cuda sdk for windows) [solved]

remove triton==2.0.0
from requirements.txt because for linux (i dont know how to fix)

**Comment by huiyichanmian** [comment]
There is an issue with installing on Windows, you can view this video：
https://www.bilibili.com/video/BV1ig4y1f7BQ/?share_source=copy_web&vd_source=842db193ae3e8fc29019a57821e30000

**Comment by EKI-INDRADI** [comment]
```sh
conda create -n m_animate python=3.10 -y
conda activate m_animate
pip install --upgrade pip
pip install -r requirements.txt

pip uninstall torch
pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cu118

python -m magicanimate.pipelines.animation --config configs\prompts\animation.yaml
python -m magicanimate.pipelines.animation --config configs\prompts\animation.yaml --dist
```


ERROR TRITON & MEMORY ALLOCATION (RTX 3080 10GB)

```sh

(m_animate) V:\_ANIMATION\MAGIC_ANIMATE\magic-animate>python -m magicanimate.pipelines.animation --config configs\prompts\animation.yaml
V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\pipeline_animation.py:43: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5\unet ...
### missing keys: 560;
### unexpected keys: 0;
### Temporal Module Parameters: 417.1376 M
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'addition_time_embed_dim': None, 'conditioning_channels': 3, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'global_pool_conditions': False, 'num_attention_heads': None, 'transformer_layers_per_block': 1} were passed to ControlNetModel, but are not expected and will be ignored. Please verify your config.json configuration file.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
It is recommended to provide `attention_head_dim` when calling `get_down_block`. Defaulting `attention_head_dim` to 8.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\pipeline_animation.py:103: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.21.4",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": false,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "steps_offset": 0,
  "thresholding": false,
  "timestep_spacing": "leading",
  "trained_betas": null
}
 is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("steps_offset!=1", "1.0.0", deprecation_message, standard_warn=False)
V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\pipeline_animation.py:116: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.21.4",
  "beta_end": 0.012,
  "beta_schedule": "linear",
  "beta_start": 0.00085,
  "clip_sample": true,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": false,
  "sample_max_value": 1.0,
  "set_alpha_to_one": true,
  "steps_offset": 1,
  "thresholding": false,
  "timestep_spacing": "leading",
  "trained_betas": null
}
 has not set the configuration `clip_sample`. `clip_sample` should be set to False in the configuration file. Please make sure to update the config accordingly as not setting `clip_sample` in the config might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
  deprecate("clip_sample not set", "1.0.0", deprecation_message, standard_warn=False)
  0%|                                                                                                                                         | 0/6 [00:00<?, ?it/s]current seed: 1
V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\pipeline_animation.py:624: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet3DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet3DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels
  4%|█████                                                                                                                           | 1/25 [00:14<05:45, 14.41s/it]
  0%|                                                                                                                                         | 0/6 [00:19<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\animation.py", line 282, in <module>
    run(args)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\animation.py", line 271, in run
    main(args)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\animation.py", line 197, in main
    sample = pipeline(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\pipelines\pipeline_animation.py", line 738, in __call__
    pred = self.unet(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\models\unet_controlnet.py", line 462, in forward
    sample = upsample_block(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\models\unet_3d_blocks.py", line 653, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\models\attention.py", line 136, in forward
    hidden_states = block(
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "V:\_ANIMATION\MAGIC_ANIMATE\magic-animate\magicanimate\models\mutual_self_attention.py", line 272, in hacked_basic_transformer_inner_forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\diffusers\models\attention.py", line 307, in forward
    hidden_states = module(hidden_states, scale)
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NGXCRYPT-2ND\.conda\envs\m_animate\lib\site-packages\diffusers\models\attention.py", line 356, in forward
    return hidden_states * self.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 10.00 GiB total capacity; 8.34 GiB already allocated; 0 bytes free; 9.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

(m_animate) V:\_ANIMATION\MAGIC_ANIMATE\magic-animate>

```

**Comment by EKI-INDRADI** [comment]
> There is an issue with installing on Windows, you can view this video： https://www.bilibili.com/video/BV1ig4y1f7BQ/?share_source=copy_web&vd_source=842db193ae3e8fc29019a57821e30000

thanks for sharing  . . .but resolution video very low

**Comment by EKI-INDRADI** [comment]
solved https://github.com/EKI-INDRADI/magic-animate-for-windows-rnd-20231206
