### ISSUE TITLE
output path file not found in run animate_dist or gradio_animate_dist

### ISSUE THREAD

**Issue by Alexjustas2011** [magic-research/magic-animate#89]
File "C:\magic-animate\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\magic-animate\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\magic-animate\venv\lib\site-packages\gradio\blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\magic-animate\venv\lib\site-packages\gradio\components\video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\magic-animate\venv\lib\site-packages\gradio\components\video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "C:\magic-animate\venv\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\magic-animate\venv\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/outputs/2023-12-09T22-06-50.mp4'

**Comment by tutnyal** [comment]
same issue

**Comment by dedkamaroz** [comment]
I think you need to create the outputs folder first

**Comment by FurkanGozukara** [comment]
install error

it is really hard to install properly 

i have venv pip auto installer along with extra features such as auto DensePose maker and CodeFormer face improvement and video upscale 

https://github.com/magic-research/magic-animate/issues/85

**Comment by betyavan** [comment]
same issue

**Comment by sqqlyd** [comment]
> I'm having a similar issue too, my path is there:
> 
> ```python
> Traceback (most recent call last):
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/blocks.py", line 1434, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/blocks.py", line 1335, in postprocess_data
>     prediction_value = block.postprocess(prediction_value)
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/components/video.py", line 281, in postprocess
>     processed_files = (self._format_video(y), None)
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/components/video.py", line 355, in _format_video
>     video = self.make_temp_copy_if_needed(video)
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
>     temp_dir = self.hash_file(file_path)
>   File "/mnt/Samsung980Pro/arch_linux_software/anaconda3/envs/manimate/lib/python3.8/site-packages/gradio/components/base.py", line 190, in hash_file
>     with open(file_path, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'demo/outputs/2024-01-05T03-27-10.mp4'
> ```

same plus 1



`
Traceback (most recent call last):
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/blocks.py", line 1335, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/home/myserver/anaconda3/envs/manimate/lib/python3.10/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/outputs/2024-02-10T01-47-59.mp4'
`

**Comment by LinDifficulty** [comment]
I hava same issue too 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\zhangyu\\magic-animate-for-windows\\demo\\outputs\\2024-03-21T22-02-49.mp4'
`

**Comment by chhandsomed** [comment]
I Think You Should Run **GradiMate.py**.   and check error.  Because the code
`run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=True)`
in **gradio_animate_dist.py**  have not run successfully at the same time, no exception is raised.

Maybe you can check **stable-diffusion-v1-5/unet/config.json**.    **"mid_block_type": "UNetMidBlock2DCrossAttn"** can revise to **"mid_block_type": "UNetMidBlock3DCrossAttn"**.
